# Generated by Django 5.1.4 on 2025-04-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artists',
            name='genres',
        ),
        migrations.AddField(
            model_name='artists',
            name='genres',
            field=models.ManyToManyField(related_name='artists', to='users.genre'),
        ),
    ]
