# Generated by Django 5.1.4 on 2025-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='stage_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
