# Generated by Django 5.1.4 on 2025-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0003_user_phone_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(to='users.artists'),
        ),
    ]
